CREATE TABLE IF NOT EXISTS "Post" (
	"post_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"poster_id" UUID NOT NULL,
	"parent_id" INTEGER,
	"content" TEXT,
	"music_link" TEXT,
	PRIMARY KEY("post_id", "poster_id")
);




CREATE TABLE IF NOT EXISTS "Profile" (
	"user_id" UUID NOT NULL UNIQUE,
	"display_name" TEXT NOT NULL,
	PRIMARY KEY("user_id")
);


CREATE INDEX "Profile_index_0"
ON "Profile" ("display_name");
ALTER TABLE "Post"
ADD FOREIGN KEY("poster_id") REFERENCES "Profile"("user_id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "Post"
ADD FOREIGN KEY("parent_id") REFERENCES "Post"("post_id")
ON UPDATE NO ACTION ON DELETE CASCADE;